version: '3'

services:
  app:
    build: ./docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/var/www/html
    environment:
      DB_HOST: db

  db:
    image: mysql:8
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: docker

  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - php-fpm-socket:/var/run/php-fpm
      - ../:/var/www/html

volumes:
  php-fpm-socket:
  db-store: